### ISSUE TITLE
Support for multiple plots log files

### ISSUE THREAD

**Issue by cristi** [Pengor/chia-log-analysis#11]
When plotting using the CLI the -n option controls the number of plots to be created. All of these plots are piped into a single log file. I would be fantastic for the chia-log-analysis to be able to parse and extract the info about all the plots

Attached you can find a couple of logs with multiple plots: [1.log](https://github.com/Pengor/chia-log-analysis/files/6461850/1.log) [2.log](https://github.com/Pengor/chia-log-analysis/files/6461852/2.log)

Thank you very much!

**Comment by Pengor** [comment]
Thanks for example files! I will add support for these types of log files and include an additional line of output to the CLI that indicates each plot that was parsed in a file.

**Comment by cristi** [comment]
Thank you!
