### ISSUE TITLE
Time format and additional columns

### ISSUE THREAD

**Issue by keeboudi** [Pengor/chia-log-analysis#14]
Hi - Thanks for this great tool. 

It would be great to have the times shown in HH:mm and maybe just mm for Phase 4. At the moment, I convert them in the spreadsheet each time,

Also, is there a way to add some additional columns to the table, esp. the log file name? - this would really help with identifying the settings used for that particular job (set up via Swar plot manager).

Cheers.

**Comment by Pengor** [comment]
Thanks for the feedback, the first suggestion is covered by issue #10 and the second (log file name) by PR #12 so I am marking this as a duplicate.
