### ISSUE TITLE
Change format of *Start date* data

### ISSUE THREAD

**Issue by Pengor** [Pengor/chia-log-analysis#9]
Due to the default format of the Chia plotter log *Start date* data it is not easily sortable by spreadsheet applications once Chia Log Analysis has output a CSV file. Chia Log Analysis should interpret the string from the log and output it in a more easily sortable format such as: `YYYY-MM-DD hh:mm:ss`

**Comment by koninka** [comment]
This will be great! Do you have any estimations about releasing this feature?
